POST http://localhost:9090/register HTTP/1.1 
# POST http://localhost:9080/api/user/register
Content-Type: application/json 


{ 
  "name": "javeeth", 
  "userName": "javeeth", 
  "email": "javeeth@gmail.com", 
  "password": "1234567"
} 

### To Login User  
POST http://localhost:9090/login
Content-Type: application/json

{
  "email": "javeeth@gmail.com",
  "password": "1234567"
}


### To Logun another User 

http://localhost:9090/get_user_and_profile
Content-Type: application/json 


{
  "token": "c082653cbec675643574636b0fd7901a5dedf3cea2435818e75b484f77e9053f"
}


### To Update Profile Data  

POST http://localhost:9090/update_profile_data HTTP/1.1 

Content-Type: application/json 

 

{ 

    "token": "c082653cbec675643574636b0fd7901a5dedf3cea2435818e75b484f77e9053f", 

    "bio": "I'm a Software Engineer at Amazon and working on upgrading myself.", 

    "currentPost": "Software Engineer II at Amazon", 

    "pastWork": [ 

        { 

            "company": "Microsoft", 

            "position": "Software Engineer", 

            "years": 2 

        } 

    ], 

    "education": [ 

        { 

            "school": "IIT Delhi", 

            "degree": "B.Tech", 

            "fieldOfStudy": "Computer Science" 

        } 

    ] 

} 

 

### To get all Users Profile  

GET http://localhost:9090/get_all_users HTTP/1.1 