POST http://localhost:9090/register HTTP/1.1 
# POST http://localhost:9080/api/user/register
Content-Type: application/json 


{ 
  "name": "adil", 
  "userName": "adil", 
  "email": "adil@gmail.com", 
  "password": "1234567"
} 

### To Login User  
POST http://localhost:9090/login
Content-Type: application/json

{
  "email": "adil@gmail.com",
  "password": "1234567"
}


### To Logun another User 

POST http://localhost:9090/get_user_and_profile
Content-Type: application/json 


{
  "token": "1a22747fcf5a9c84f51d67b453d37d1b0f66fc9e770d7db219a8b6a680e8d006"
}


### To Update Profile Data  

POST http://localhost:9090/update_profile_data HTTP/1.1 

Content-Type: application/json 

 

{ 

    "token": "1a22747fcf5a9c84f51d67b453d37d1b0f66fc9e770d7db219a8b6a680e8d006", 

    "bio": "I'm a Software Engineer at Amazon and working on upgrading myself.", 

    "currentPost": "Software Engineer II at Amazon", 

    "pastWork": [ 

        { 

            "company": "Microsoft", 

            "position": "Software Engineer", 

            "years": 2 

        } 

    ], 

    "education": [ 

        { 

            "school": "IIT Delhi", 

            "degree": "B.Tech", 

            "fieldOfStudy": "Computer Science" 

        } 

    ] 

} 

### to download resume

POST http://localhost:9090/user/download_resume
Content-Type: application/json


{
  "id": "6937ee94c73d6ad74153c951"
}



### To get all Users Profile  

GET http://localhost:9090/get_all_users HTTP/1.1 